platform_locations = ["northeurope", "westeurope", "eastus", "centralus", "westus"]
sevpool_count = [2, 0, 3, 0, 0]
tdxpool_count = [0, 0, 0, 3, 0]
nonteepool_count = [0, 0, 0, 0, 0]
clientpool_count = [0, 0, 0, 0, 3]
