platform_locations = ["centralus", "eastus", "westeurope", "northeurope", "westus"]
tdxpool_count = [2, 0, 2, 0, 0]
sevpool_count = [0, 2, 0, 2, 1]
nonteepool_count = [0, 0, 0, 0, 0]
clientpool_count = [5, 0, 0, 0, 0]
