# platform_locations = ["centralus", "eastus", "westeurope", "northeurope", "westus"]
platform_locations = ["eastus2", "eastus", "westus", "centralus", "westeurope"]
tdxpool_count =    [2, 0, 0, 2, 0]
sevpool_count =    [0, 2, 2, 0, 1]
nonteepool_count = [0, 0, 0, 0, 0]
clientpool_count = [5, 0, 0, 0, 0]
