platform_locations = ["centralus", "eastus", "westeurope", "northeurope", "westus"]
tdxpool_count = [3, 0, 3, 0, 0]
sevpool_count = [0, 2, 0, 1, 0]
nonteepool_count = [0, 0, 0, 0, 0]
clientpool_count = [5, 0, 0, 0, 0]
