workdir = "deployment_artifacts"
project_home = "https://github.com/grapheo12/pirateship"

[deployment_config]
mode = "lan"
# mode = "lan-nontee"
# mode = "lan-tdx"
ssh_key = "cluster_key.pem"
ssh_user = "pftadmin"
node_port_base = 3000


[node_config]

[node_config.net_config]
client_max_retry = 10

[node_config.rpc_config]
recv_buffer_size = 32768
channel_depth = 1000

[node_config.consensus_config]
commit_index_gap_soft = 100
commit_index_gap_hard = 5000
liveness_u = 2
max_backlog_batch_size = 1000
signature_max_delay_blocks = 10
signature_max_delay_ms = 102 # roughly batch_max_delay_ms * signature_max_delay_blocks
num_crypto_workers = 5
view_timeout_ms = 40000
batch_max_delay_ms = 2

[node_config.consensus_config.log_storage_config.RocksDB]
write_buffer_size = 2_147_483_648
# write_buffer_size = 67_108_864
max_write_buffer_number = 8
max_write_buffers_to_merge = 1

[node_config.app_config]
logger_stats_report_ms = 100
checkpoint_interval_ms = 1000

[node_config.evil_config]
simulate_byzantine_behavior = false
byzantine_start_block = 0


[client_config]
full_duplex = true
client_sub_id = 0       # This is filled up later by the caller code.

[client_config.net_config]
client_max_retry = 10

[client_config.workload_config]
num_requests = 100_000_000
request_config = "Blanks"
max_concurrent_requests = 32

[[experiments]]
name = "async_disk"
repeats = 1
num_nodes = 7
node_distribution = "uniform"
build_command = "make"
duration = 60

[experiments.sweeping_parameters]
num_clients = [10, 20, 30, 50, 100, 200, 400, 500, 600]

# [[experiments]]
# name = "sync_disk"
# repeats = 1
# num_nodes = 7
# node_distribution = "uniform"
# build_command = "make pirateship_logger_syncstorage"
# duration = 120

# [experiments.sweeping_parameters]
# num_clients = [800]

# [[experiments]]
# name = "no_disk"
# repeats = 1
# num_nodes = 7
# node_distribution = "uniform"
# build_command = "make pirateship_logger_nostorage"
# duration = 180

# [experiments.sweeping_parameters]
# num_clients = [800]





[[results]]
name = "tput_latency_client_sweep"
plotter = "tput_latency_sweep"
ramp_up = 10
ramp_down = 10
output = "lan_final.pdf"
force_parse = true
# skip_indices = [7]

[results.legends]
# Experiment group to legend mapping
async_disk = "async_disk+byz"
# sync_disk = "sync_disk"
no_disk = "no_disk"


[results.font]
size = 55
