workdir = "deployment_artifacts"
project_home = "https://github.com/grapheo12/pirateship"

[deployment_config]
mode = "lan"
ssh_key = "cluster_key.pem"
ssh_user = "pftadmin"
node_port_base = 3000


[node_config]

[node_config.net_config]
client_max_retry = 10

[node_config.rpc_config]
recv_buffer_size = 32768
channel_depth = 1000

[node_config.consensus_config]
commit_index_gap_soft = 250
commit_index_gap_hard = 500
liveness_u = 2
max_backlog_batch_size = 100
signature_max_delay_blocks = 10
signature_max_delay_ms = 102 # roughly batch_max_delay_ms * signature_max_delay_blocks
num_crypto_workers = 5
view_timeout_ms = 4000
batch_max_delay_ms = 2

[node_config.consensus_config.log_storage_config.RocksDB]
write_buffer_size = 2147483648
max_write_buffer_number = 1
max_write_buffers_to_merge = 1

[node_config.app_config]
logger_stats_report_ms = 100
checkpoint_interval_ms = 1000

[node_config.evil_config]
simulate_byzantine_behavior = false
byzantine_start_block = 0

[client_config]
getDistribution = 50
workers_per_client = 8
workload = "kms"



# [[experiments]]
# name = "svr3"
# type = "app"
# repeats = 1
# num_nodes = 7
# num_clients = 3_000
# build_command = "make contrib"
# duration = 300


# [[experiments]]
# name = "kms"
# type = "app"
# repeats = 1
# num_nodes = 7
# num_clients = 3_000
# build_command = "make contrib"
# duration = 300

# [experiments.client_config]
# workload = "kms"

[[experiments]]
name = "banking"
type = "app"
repeats = 1
num_nodes = 7
num_clients = 3_000
build_command = "make contrib"
duration = 120

[experiments.client_config]
workload = "smallbank"

[experiments.sweeping_parameters.client_config]
payment_threshold = [1, 10, 100, 1000, 10000]


[[results]]
name = "tput_latency_client_sweep"
plotter = "tput_latency_sweep"
ramp_up = 15
ramp_down = 15
output = "lan_final.pdf"
force_parse = true
# skip_indices = [7]

[results.legends]
# Experiment group to legend mapping
# pirateship = "ps(sig=10)+byz"
# pirateship_sig_1 = "ps(sig=1)+byz"
# hotstuff = "hotstuff+onlybyz"
# engraft = "engraft+onlybyz"
# signed_raft = "signed_raft"
# autobahn = "autobahn"

[results.font]
size = 55
