workdir = "deployment_artifacts"
project_home = "https://github.com/grapheo12/pirateship"

[deployment_config]
mode = "lan-jumbo"
ssh_key = "cluster_key.pem"
ssh_user = "pftadmin"
node_port_base = 3000


[node_config]

[node_config.net_config]
client_max_retry = 10

[node_config.rpc_config]
recv_buffer_size = 32768
channel_depth = 1000

[node_config.consensus_config]
commit_index_gap_soft = 250
commit_index_gap_hard = 500
liveness_u = 2
max_backlog_batch_size = 1000
signature_max_delay_blocks = 50
signature_max_delay_ms = 10000
num_crypto_workers = 5
view_timeout_ms = 4000
batch_max_delay_ms = 5

[node_config.consensus_config.log_storage_config.RocksDB]
write_buffer_size = 2147483648
max_write_buffer_number = 1
max_write_buffers_to_merge = 1

[node_config.app_config]
logger_stats_report_ms = 100

[node_config.evil_config]
simulate_byzantine_behavior = false
byzantine_start_block = 0


[client_config]

[client_config.net_config]
client_max_retry = 10

[client_config.workload_config]
num_requests = 100_000_000
request_config = "Blanks"

[[experiments]]
name = "tdx"
repeats = 3
num_nodes = 4
num_clients = 2000
client_region = 0 # This comes from the tfvars file used here.
node_distribution = "tdx_only"
duration = 120

[experiments.sweeping_parameters]
build_command = ["make", "make pirateship_logger_nostorage"]

[[experiments]]
name = "sev"
repeats = 3
num_nodes = 4
num_clients = 2000
node_distribution = "sev_only"
client_region = 1 # This comes from the tfvars file used here.
duration = 120

[experiments.sweeping_parameters]
build_command = ["make", "make pirateship_logger_nostorage"]


[[experiments]]
name = "nontee"
repeats = 3
num_nodes = 4
num_clients = 2000
client_region = 0
node_distribution = "nontee_only"
duration = 120

[experiments.sweeping_parameters]
build_command = ["make", "make pirateship_logger_nostorage"]



[[results]]
name = "tput_rw_sweep"
plotter = "stacked_bar_graph"
ramp_up = 30
ramp_down = 30
output = "storage_effect.pdf"
xlabels = ["Disk", "In-Mem"]

[results.legends]
tdx = "TDX"
sev = "SEV-SNP"
nontee = "Non-TEE"
